spring:
  application:
    name: LAB_MODEL
  datasource:
    users:
      jdbc-url: jdbc:mysql://localhost:3306/users_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1q2w3e
    gallery:
      jdbc-url: jdbc:mysql://localhost:3306/gallery_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1q2w3e
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
      javax:
        persistence:
          schema-generation:
            database:
              action: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 364670719208-35gnql2klufnp548ob1d4lppki8drk35.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
  messages:
    basename: validation

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.example.rest_api: INFO
    com.example.rest_api.service.UserService: DEBUG
