spring:
  application:
    name: LAB_MODEL
  datasource:
    users:
      jdbc-url: jdbc:mysql://localhost:3306/users_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1q2w3e
    gallery:
      jdbc-url: jdbc:mysql://localhost:3306/gallery_db
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1q2w3e
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
      javax:
        persistence:
          schema-generation:
            database:
              action: create
    gallery:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update
    users:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        ddl-auto: update

  messages:
    basename: validation

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.example.rest_api: INFO
    com.example.rest_api.service.UserService: DEBUG
